import { styled } from "@/styled-system/jsx";
import "./globals.css";
import type { Metadata } from "next";
import { Fraunces, Climate_Crisis } from "next/font/google";
import { css, cx } from "@/styled-system/css";

const fraunces = Fraunces({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-fraunces",
});

const climateCrisis = Climate_Crisis({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-climate_crisis",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const body = css({
  background: "background",
  color: "text",
  marginLeft: "5rem",
  padding: "1rem",
  scrollBehavior: "smooth"
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={css({ fontSize: "16px" })}>
      <body className={cx(fraunces.className, body)}>
        {children}
      </body>
    </html>
  );
}
